// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft-java-example/src/main/java/com/github/jyzhao/raft/example/server/auction.proto

package com.github.wenweihu86.raft.example.server.service;

public final class AuctionProto {
  private AuctionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CreateAuctionItemRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:service.CreateAuctionItemRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string owner = 1;</code>
     */
    boolean hasOwner();
    /**
     * <code>optional string owner = 1;</code>
     */
    java.lang.String getOwner();
    /**
     * <code>optional string owner = 1;</code>
     */
    com.google.protobuf.ByteString
        getOwnerBytes();

    /**
     * <code>optional string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional float minVal = 3;</code>
     */
    boolean hasMinVal();
    /**
     * <code>optional float minVal = 3;</code>
     */
    float getMinVal();
  }
  /**
   * Protobuf type {@code service.CreateAuctionItemRequest}
   */
  public static final class CreateAuctionItemRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:service.CreateAuctionItemRequest)
      CreateAuctionItemRequestOrBuilder {
    // Use CreateAuctionItemRequest.newBuilder() to construct.
    private CreateAuctionItemRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CreateAuctionItemRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CreateAuctionItemRequest defaultInstance;
    public static CreateAuctionItemRequest getDefaultInstance() {
      return defaultInstance;
    }

    public CreateAuctionItemRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CreateAuctionItemRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              owner_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              minVal_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.wenweihu86.raft.example.server.service.AuctionProto.internal_static_service_CreateAuctionItemRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.wenweihu86.raft.example.server.service.AuctionProto.internal_static_service_CreateAuctionItemRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemRequest.class, com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<CreateAuctionItemRequest> PARSER =
        new com.google.protobuf.AbstractParser<CreateAuctionItemRequest>() {
      public CreateAuctionItemRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreateAuctionItemRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CreateAuctionItemRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int OWNER_FIELD_NUMBER = 1;
    private java.lang.Object owner_;
    /**
     * <code>optional string owner = 1;</code>
     */
    public boolean hasOwner() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string owner = 1;</code>
     */
    public java.lang.String getOwner() {
      java.lang.Object ref = owner_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          owner_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string owner = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOwnerBytes() {
      java.lang.Object ref = owner_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        owner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MINVAL_FIELD_NUMBER = 3;
    private float minVal_;
    /**
     * <code>optional float minVal = 3;</code>
     */
    public boolean hasMinVal() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional float minVal = 3;</code>
     */
    public float getMinVal() {
      return minVal_;
    }

    private void initFields() {
      owner_ = "";
      name_ = "";
      minVal_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getOwnerBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, minVal_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getOwnerBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, minVal_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code service.CreateAuctionItemRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:service.CreateAuctionItemRequest)
        com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.wenweihu86.raft.example.server.service.AuctionProto.internal_static_service_CreateAuctionItemRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.wenweihu86.raft.example.server.service.AuctionProto.internal_static_service_CreateAuctionItemRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemRequest.class, com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemRequest.Builder.class);
      }

      // Construct using com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        owner_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        minVal_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.wenweihu86.raft.example.server.service.AuctionProto.internal_static_service_CreateAuctionItemRequest_descriptor;
      }

      public com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemRequest getDefaultInstanceForType() {
        return com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemRequest.getDefaultInstance();
      }

      public com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemRequest build() {
        com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemRequest buildPartial() {
        com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemRequest result = new com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.owner_ = owner_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.minVal_ = minVal_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemRequest) {
          return mergeFrom((com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemRequest other) {
        if (other == com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemRequest.getDefaultInstance()) return this;
        if (other.hasOwner()) {
          bitField0_ |= 0x00000001;
          owner_ = other.owner_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasMinVal()) {
          setMinVal(other.getMinVal());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object owner_ = "";
      /**
       * <code>optional string owner = 1;</code>
       */
      public boolean hasOwner() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string owner = 1;</code>
       */
      public java.lang.String getOwner() {
        java.lang.Object ref = owner_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            owner_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string owner = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOwnerBytes() {
        java.lang.Object ref = owner_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          owner_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string owner = 1;</code>
       */
      public Builder setOwner(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        owner_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string owner = 1;</code>
       */
      public Builder clearOwner() {
        bitField0_ = (bitField0_ & ~0x00000001);
        owner_ = getDefaultInstance().getOwner();
        onChanged();
        return this;
      }
      /**
       * <code>optional string owner = 1;</code>
       */
      public Builder setOwnerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        owner_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private float minVal_ ;
      /**
       * <code>optional float minVal = 3;</code>
       */
      public boolean hasMinVal() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional float minVal = 3;</code>
       */
      public float getMinVal() {
        return minVal_;
      }
      /**
       * <code>optional float minVal = 3;</code>
       */
      public Builder setMinVal(float value) {
        bitField0_ |= 0x00000004;
        minVal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float minVal = 3;</code>
       */
      public Builder clearMinVal() {
        bitField0_ = (bitField0_ & ~0x00000004);
        minVal_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:service.CreateAuctionItemRequest)
    }

    static {
      defaultInstance = new CreateAuctionItemRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:service.CreateAuctionItemRequest)
  }

  public interface CreateAuctionItemResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:service.CreateAuctionItemResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string response = 1;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional string response = 1;</code>
     */
    java.lang.String getResponse();
    /**
     * <code>optional string response = 1;</code>
     */
    com.google.protobuf.ByteString
        getResponseBytes();
  }
  /**
   * Protobuf type {@code service.CreateAuctionItemResponse}
   */
  public static final class CreateAuctionItemResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:service.CreateAuctionItemResponse)
      CreateAuctionItemResponseOrBuilder {
    // Use CreateAuctionItemResponse.newBuilder() to construct.
    private CreateAuctionItemResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CreateAuctionItemResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CreateAuctionItemResponse defaultInstance;
    public static CreateAuctionItemResponse getDefaultInstance() {
      return defaultInstance;
    }

    public CreateAuctionItemResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CreateAuctionItemResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              response_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.wenweihu86.raft.example.server.service.AuctionProto.internal_static_service_CreateAuctionItemResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.wenweihu86.raft.example.server.service.AuctionProto.internal_static_service_CreateAuctionItemResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemResponse.class, com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<CreateAuctionItemResponse> PARSER =
        new com.google.protobuf.AbstractParser<CreateAuctionItemResponse>() {
      public CreateAuctionItemResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreateAuctionItemResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CreateAuctionItemResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RESPONSE_FIELD_NUMBER = 1;
    private java.lang.Object response_;
    /**
     * <code>optional string response = 1;</code>
     */
    public boolean hasResponse() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string response = 1;</code>
     */
    public java.lang.String getResponse() {
      java.lang.Object ref = response_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          response_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string response = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResponseBytes() {
      java.lang.Object ref = response_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        response_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      response_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getResponseBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getResponseBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code service.CreateAuctionItemResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:service.CreateAuctionItemResponse)
        com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.wenweihu86.raft.example.server.service.AuctionProto.internal_static_service_CreateAuctionItemResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.wenweihu86.raft.example.server.service.AuctionProto.internal_static_service_CreateAuctionItemResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemResponse.class, com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemResponse.Builder.class);
      }

      // Construct using com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        response_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.wenweihu86.raft.example.server.service.AuctionProto.internal_static_service_CreateAuctionItemResponse_descriptor;
      }

      public com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemResponse getDefaultInstanceForType() {
        return com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemResponse.getDefaultInstance();
      }

      public com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemResponse build() {
        com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemResponse buildPartial() {
        com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemResponse result = new com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.response_ = response_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemResponse) {
          return mergeFrom((com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemResponse other) {
        if (other == com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemResponse.getDefaultInstance()) return this;
        if (other.hasResponse()) {
          bitField0_ |= 0x00000001;
          response_ = other.response_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.wenweihu86.raft.example.server.service.AuctionProto.CreateAuctionItemResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object response_ = "";
      /**
       * <code>optional string response = 1;</code>
       */
      public boolean hasResponse() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string response = 1;</code>
       */
      public java.lang.String getResponse() {
        java.lang.Object ref = response_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            response_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string response = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResponseBytes() {
        java.lang.Object ref = response_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          response_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string response = 1;</code>
       */
      public Builder setResponse(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        response_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string response = 1;</code>
       */
      public Builder clearResponse() {
        bitField0_ = (bitField0_ & ~0x00000001);
        response_ = getDefaultInstance().getResponse();
        onChanged();
        return this;
      }
      /**
       * <code>optional string response = 1;</code>
       */
      public Builder setResponseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        response_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:service.CreateAuctionItemResponse)
    }

    static {
      defaultInstance = new CreateAuctionItemResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:service.CreateAuctionItemResponse)
  }

  public interface BidRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:service.BidRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string bidder = 1;</code>
     */
    boolean hasBidder();
    /**
     * <code>optional string bidder = 1;</code>
     */
    java.lang.String getBidder();
    /**
     * <code>optional string bidder = 1;</code>
     */
    com.google.protobuf.ByteString
        getBidderBytes();

    /**
     * <code>optional string biddedItem = 2;</code>
     */
    boolean hasBiddedItem();
    /**
     * <code>optional string biddedItem = 2;</code>
     */
    java.lang.String getBiddedItem();
    /**
     * <code>optional string biddedItem = 2;</code>
     */
    com.google.protobuf.ByteString
        getBiddedItemBytes();

    /**
     * <code>optional float bidVal = 3;</code>
     */
    boolean hasBidVal();
    /**
     * <code>optional float bidVal = 3;</code>
     */
    float getBidVal();
  }
  /**
   * Protobuf type {@code service.BidRequest}
   */
  public static final class BidRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:service.BidRequest)
      BidRequestOrBuilder {
    // Use BidRequest.newBuilder() to construct.
    private BidRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BidRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BidRequest defaultInstance;
    public static BidRequest getDefaultInstance() {
      return defaultInstance;
    }

    public BidRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BidRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              bidder_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              biddedItem_ = bs;
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              bidVal_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.wenweihu86.raft.example.server.service.AuctionProto.internal_static_service_BidRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.wenweihu86.raft.example.server.service.AuctionProto.internal_static_service_BidRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.wenweihu86.raft.example.server.service.AuctionProto.BidRequest.class, com.github.wenweihu86.raft.example.server.service.AuctionProto.BidRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<BidRequest> PARSER =
        new com.google.protobuf.AbstractParser<BidRequest>() {
      public BidRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BidRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BidRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BIDDER_FIELD_NUMBER = 1;
    private java.lang.Object bidder_;
    /**
     * <code>optional string bidder = 1;</code>
     */
    public boolean hasBidder() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string bidder = 1;</code>
     */
    public java.lang.String getBidder() {
      java.lang.Object ref = bidder_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bidder_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string bidder = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBidderBytes() {
      java.lang.Object ref = bidder_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bidder_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIDDEDITEM_FIELD_NUMBER = 2;
    private java.lang.Object biddedItem_;
    /**
     * <code>optional string biddedItem = 2;</code>
     */
    public boolean hasBiddedItem() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string biddedItem = 2;</code>
     */
    public java.lang.String getBiddedItem() {
      java.lang.Object ref = biddedItem_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          biddedItem_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string biddedItem = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBiddedItemBytes() {
      java.lang.Object ref = biddedItem_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        biddedItem_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIDVAL_FIELD_NUMBER = 3;
    private float bidVal_;
    /**
     * <code>optional float bidVal = 3;</code>
     */
    public boolean hasBidVal() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional float bidVal = 3;</code>
     */
    public float getBidVal() {
      return bidVal_;
    }

    private void initFields() {
      bidder_ = "";
      biddedItem_ = "";
      bidVal_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getBidderBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getBiddedItemBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, bidVal_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getBidderBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getBiddedItemBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, bidVal_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.BidRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.BidRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.BidRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.BidRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.BidRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.BidRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.BidRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.BidRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.BidRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.BidRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.wenweihu86.raft.example.server.service.AuctionProto.BidRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code service.BidRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:service.BidRequest)
        com.github.wenweihu86.raft.example.server.service.AuctionProto.BidRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.wenweihu86.raft.example.server.service.AuctionProto.internal_static_service_BidRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.wenweihu86.raft.example.server.service.AuctionProto.internal_static_service_BidRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.wenweihu86.raft.example.server.service.AuctionProto.BidRequest.class, com.github.wenweihu86.raft.example.server.service.AuctionProto.BidRequest.Builder.class);
      }

      // Construct using com.github.wenweihu86.raft.example.server.service.AuctionProto.BidRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        bidder_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        biddedItem_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        bidVal_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.wenweihu86.raft.example.server.service.AuctionProto.internal_static_service_BidRequest_descriptor;
      }

      public com.github.wenweihu86.raft.example.server.service.AuctionProto.BidRequest getDefaultInstanceForType() {
        return com.github.wenweihu86.raft.example.server.service.AuctionProto.BidRequest.getDefaultInstance();
      }

      public com.github.wenweihu86.raft.example.server.service.AuctionProto.BidRequest build() {
        com.github.wenweihu86.raft.example.server.service.AuctionProto.BidRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.wenweihu86.raft.example.server.service.AuctionProto.BidRequest buildPartial() {
        com.github.wenweihu86.raft.example.server.service.AuctionProto.BidRequest result = new com.github.wenweihu86.raft.example.server.service.AuctionProto.BidRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.bidder_ = bidder_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.biddedItem_ = biddedItem_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.bidVal_ = bidVal_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.wenweihu86.raft.example.server.service.AuctionProto.BidRequest) {
          return mergeFrom((com.github.wenweihu86.raft.example.server.service.AuctionProto.BidRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.wenweihu86.raft.example.server.service.AuctionProto.BidRequest other) {
        if (other == com.github.wenweihu86.raft.example.server.service.AuctionProto.BidRequest.getDefaultInstance()) return this;
        if (other.hasBidder()) {
          bitField0_ |= 0x00000001;
          bidder_ = other.bidder_;
          onChanged();
        }
        if (other.hasBiddedItem()) {
          bitField0_ |= 0x00000002;
          biddedItem_ = other.biddedItem_;
          onChanged();
        }
        if (other.hasBidVal()) {
          setBidVal(other.getBidVal());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.wenweihu86.raft.example.server.service.AuctionProto.BidRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.wenweihu86.raft.example.server.service.AuctionProto.BidRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object bidder_ = "";
      /**
       * <code>optional string bidder = 1;</code>
       */
      public boolean hasBidder() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string bidder = 1;</code>
       */
      public java.lang.String getBidder() {
        java.lang.Object ref = bidder_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            bidder_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string bidder = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBidderBytes() {
        java.lang.Object ref = bidder_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bidder_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string bidder = 1;</code>
       */
      public Builder setBidder(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        bidder_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string bidder = 1;</code>
       */
      public Builder clearBidder() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bidder_ = getDefaultInstance().getBidder();
        onChanged();
        return this;
      }
      /**
       * <code>optional string bidder = 1;</code>
       */
      public Builder setBidderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        bidder_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object biddedItem_ = "";
      /**
       * <code>optional string biddedItem = 2;</code>
       */
      public boolean hasBiddedItem() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string biddedItem = 2;</code>
       */
      public java.lang.String getBiddedItem() {
        java.lang.Object ref = biddedItem_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            biddedItem_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string biddedItem = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBiddedItemBytes() {
        java.lang.Object ref = biddedItem_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          biddedItem_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string biddedItem = 2;</code>
       */
      public Builder setBiddedItem(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        biddedItem_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string biddedItem = 2;</code>
       */
      public Builder clearBiddedItem() {
        bitField0_ = (bitField0_ & ~0x00000002);
        biddedItem_ = getDefaultInstance().getBiddedItem();
        onChanged();
        return this;
      }
      /**
       * <code>optional string biddedItem = 2;</code>
       */
      public Builder setBiddedItemBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        biddedItem_ = value;
        onChanged();
        return this;
      }

      private float bidVal_ ;
      /**
       * <code>optional float bidVal = 3;</code>
       */
      public boolean hasBidVal() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional float bidVal = 3;</code>
       */
      public float getBidVal() {
        return bidVal_;
      }
      /**
       * <code>optional float bidVal = 3;</code>
       */
      public Builder setBidVal(float value) {
        bitField0_ |= 0x00000004;
        bidVal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float bidVal = 3;</code>
       */
      public Builder clearBidVal() {
        bitField0_ = (bitField0_ & ~0x00000004);
        bidVal_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:service.BidRequest)
    }

    static {
      defaultInstance = new BidRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:service.BidRequest)
  }

  public interface BidResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:service.BidResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string response = 1;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional string response = 1;</code>
     */
    java.lang.String getResponse();
    /**
     * <code>optional string response = 1;</code>
     */
    com.google.protobuf.ByteString
        getResponseBytes();
  }
  /**
   * Protobuf type {@code service.BidResponse}
   */
  public static final class BidResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:service.BidResponse)
      BidResponseOrBuilder {
    // Use BidResponse.newBuilder() to construct.
    private BidResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BidResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BidResponse defaultInstance;
    public static BidResponse getDefaultInstance() {
      return defaultInstance;
    }

    public BidResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BidResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              response_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.wenweihu86.raft.example.server.service.AuctionProto.internal_static_service_BidResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.wenweihu86.raft.example.server.service.AuctionProto.internal_static_service_BidResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.wenweihu86.raft.example.server.service.AuctionProto.BidResponse.class, com.github.wenweihu86.raft.example.server.service.AuctionProto.BidResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<BidResponse> PARSER =
        new com.google.protobuf.AbstractParser<BidResponse>() {
      public BidResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BidResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BidResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RESPONSE_FIELD_NUMBER = 1;
    private java.lang.Object response_;
    /**
     * <code>optional string response = 1;</code>
     */
    public boolean hasResponse() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string response = 1;</code>
     */
    public java.lang.String getResponse() {
      java.lang.Object ref = response_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          response_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string response = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResponseBytes() {
      java.lang.Object ref = response_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        response_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      response_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getResponseBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getResponseBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.BidResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.BidResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.BidResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.BidResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.BidResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.BidResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.BidResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.BidResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.BidResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.wenweihu86.raft.example.server.service.AuctionProto.BidResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.wenweihu86.raft.example.server.service.AuctionProto.BidResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code service.BidResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:service.BidResponse)
        com.github.wenweihu86.raft.example.server.service.AuctionProto.BidResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.wenweihu86.raft.example.server.service.AuctionProto.internal_static_service_BidResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.wenweihu86.raft.example.server.service.AuctionProto.internal_static_service_BidResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.wenweihu86.raft.example.server.service.AuctionProto.BidResponse.class, com.github.wenweihu86.raft.example.server.service.AuctionProto.BidResponse.Builder.class);
      }

      // Construct using com.github.wenweihu86.raft.example.server.service.AuctionProto.BidResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        response_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.wenweihu86.raft.example.server.service.AuctionProto.internal_static_service_BidResponse_descriptor;
      }

      public com.github.wenweihu86.raft.example.server.service.AuctionProto.BidResponse getDefaultInstanceForType() {
        return com.github.wenweihu86.raft.example.server.service.AuctionProto.BidResponse.getDefaultInstance();
      }

      public com.github.wenweihu86.raft.example.server.service.AuctionProto.BidResponse build() {
        com.github.wenweihu86.raft.example.server.service.AuctionProto.BidResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.wenweihu86.raft.example.server.service.AuctionProto.BidResponse buildPartial() {
        com.github.wenweihu86.raft.example.server.service.AuctionProto.BidResponse result = new com.github.wenweihu86.raft.example.server.service.AuctionProto.BidResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.response_ = response_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.wenweihu86.raft.example.server.service.AuctionProto.BidResponse) {
          return mergeFrom((com.github.wenweihu86.raft.example.server.service.AuctionProto.BidResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.wenweihu86.raft.example.server.service.AuctionProto.BidResponse other) {
        if (other == com.github.wenweihu86.raft.example.server.service.AuctionProto.BidResponse.getDefaultInstance()) return this;
        if (other.hasResponse()) {
          bitField0_ |= 0x00000001;
          response_ = other.response_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.wenweihu86.raft.example.server.service.AuctionProto.BidResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.wenweihu86.raft.example.server.service.AuctionProto.BidResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object response_ = "";
      /**
       * <code>optional string response = 1;</code>
       */
      public boolean hasResponse() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string response = 1;</code>
       */
      public java.lang.String getResponse() {
        java.lang.Object ref = response_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            response_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string response = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResponseBytes() {
        java.lang.Object ref = response_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          response_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string response = 1;</code>
       */
      public Builder setResponse(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        response_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string response = 1;</code>
       */
      public Builder clearResponse() {
        bitField0_ = (bitField0_ & ~0x00000001);
        response_ = getDefaultInstance().getResponse();
        onChanged();
        return this;
      }
      /**
       * <code>optional string response = 1;</code>
       */
      public Builder setResponseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        response_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:service.BidResponse)
    }

    static {
      defaultInstance = new BidResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:service.BidResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service_CreateAuctionItemRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_service_CreateAuctionItemRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service_CreateAuctionItemResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_service_CreateAuctionItemResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service_BidRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_service_BidRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service_BidResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_service_BidResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nSraft-java-example/src/main/java/com/gi" +
      "thub/jyzhao/raft/example/server/auction." +
      "proto\022\007service\"G\n\030CreateAuctionItemReque" +
      "st\022\r\n\005owner\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\016\n\006minVa" +
      "l\030\003 \001(\002\"-\n\031CreateAuctionItemResponse\022\020\n\010" +
      "response\030\001 \001(\t\"@\n\nBidRequest\022\016\n\006bidder\030\001" +
      " \001(\t\022\022\n\nbiddedItem\030\002 \001(\t\022\016\n\006bidVal\030\003 \001(\002" +
      "\"\037\n\013BidResponse\022\020\n\010response\030\001 \001(\tBA\n1com" +
      ".github.wenweihu86.raft.example.server.s" +
      "erviceB\014AuctionProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service_CreateAuctionItemRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service_CreateAuctionItemRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_service_CreateAuctionItemRequest_descriptor,
        new java.lang.String[] { "Owner", "Name", "MinVal", });
    internal_static_service_CreateAuctionItemResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service_CreateAuctionItemResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_service_CreateAuctionItemResponse_descriptor,
        new java.lang.String[] { "Response", });
    internal_static_service_BidRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service_BidRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_service_BidRequest_descriptor,
        new java.lang.String[] { "Bidder", "BiddedItem", "BidVal", });
    internal_static_service_BidResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service_BidResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_service_BidResponse_descriptor,
        new java.lang.String[] { "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
